DROP TABLE buecher IF EXISTS;
CREATE TABLE buecher
(
   id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL,
   autor varchar(255),
   fabianGelesen bit NOT NULL,
   seiten int NOT NULL,
   simoneGelesen bit NOT NULL,
   titel varchar(255),
   updateDatum timestamp,
   verlag varchar(255)
)
;


DROP TABLE customer IF EXISTS;
DROP TABLE bankAccount IF EXISTS;

CREATE TABLE customer
(
   id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL,
   email varchar(255),
   firstName varchar(255),
   lastName varchar(255)
);

CREATE TABLE bankAccount
(
   id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY NOT NULL,
   customerId integer,
   iban varchar(255)
);

ALTER TABLE bankAccount ADD FOREIGN KEY (customerId) REFERENCES customer(id);

